version: '3.8'

services:
  django:
    image: ksohyeon/amadeusflightbookingdjango:latest
    container_name: django_server
    ports:
      - "8081:8000"
    volumes:
      - ./amadeus:/code
    depends_on:
      - fastapi
    networks:
      - app_network
    env_file:
      - ~/flight-booking.env

  fastapi:
    image: ksohyeon/amadeusfastapiengine:latest
    container_name: fastapi_server
    ports:
      - "8080:8080"
    volumes:
      - ./ai:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
