name: Build and deploy container app to EC2 - flight-booking-engine

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/amadeusflightbookingdjango:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "AMADEUS_CLIENT_ID=${{secrets.AMADEUS_CLIENT_ID}}" > ~/flight-booking.env
          echo "AMADEUS_CLIENT_SECRET=${{secrets.AMADEUS_CLIENT_SECRET}}" >> ~/flight-booking.env
          echo "HOST_URL=${{secrets.HOST_URL}}" >> ~/flight-booking.env

          cd ./amadeus-flight-booking-django
          git pull
          docker-compose pull
          docker-compose up -d
